Hotfix/invite
nyeoni/eyeRsee pull request #83
Opened 2023-03-24 14:28 UTC by Kimhan-nah

## 개요

## 작업내용

## 주의사항

2023-03-25 15:03 UTC, chaejin-jen commented on src/controller/Executor.cpp
> +            ErrorHandler::handleError(client, *iter, ERR_INVITEONLYCHAN);
_i_channel_list 있으면 invite 성공하는 동작을 여기 추가해야하는지 확인 부탁드립니다.

2023-03-25 15:07 UTC, chaejin-jen commented on src/entity/Channel.cpp
> +    setMode(INVITE_ONLY_F);
+ 모드(TOPIC_PRIV_T)만 추가해주면 될 것 같습니다.
눈에 잘 들어오라고 아무 동작 안하는, INVITE_ONLY_F 를 set 해준 건가요?

2023-03-25 15:10 UTC, chaejin-jen commented on src/handler/ErrorHandler.cpp
> +    "Cannot join channel (invite only)";
저는 +i 로 냅두는거 한표 올립니당!

2023-03-25 15:12 UTC, chaejin-jen requested changes
`join()` 에서, 가입하려는 채널이 Invite only 모드의 경우 invite channel list 확인뒤 가입시키거나, 에러 띄우는거 추가 부탁드립니다!

2023-03-26 04:07 UTC, nyeoni commented
후비적

2023-03-26 05:06 UTC, Kimhan-nah commented on src/controller/Executor.cpp
> +            ErrorHandler::handleError(client, *iter, ERR_INVITEONLYCHAN);
요청하신 부분 수정해서 올렸습니다!

2023-03-26 06:23 UTC, Kimhan-nah commented on src/entity/Channel.cpp
> +    setMode(INVITE_ONLY_F);
요청하신 부분 수정했습니다~

2023-03-26 06:24 UTC, Kimhan-nah commented on src/handler/ErrorHandler.cpp
> +    "Cannot join channel (invite only)";
inspircd를 참고해서 invite only로 두겠습니다!

2023-03-26 06:26 UTC, chaejin-jen commented on include/handler/ResponseHandler.hpp
> +    static void handleInviteResponse(ConnectSocket *invitor,
inviter 로 수정 부탁드려요 호호

2023-03-26 06:27 UTC, nyeoni approved these changes
뿡뿡 ๑ `ᶺ´ ๑

2023-03-26 06:27 UTC, chaejin-jen commented on src/controller/ChannelController.cpp
> +    std::set<Client *> invited_clients = channel->getInvitedClients();
& 적극 활용 추천~!

2023-03-26 06:30 UTC, chaejin-jen commented on src/controller/Executor.cpp
> +                   !channel_controller.isInvitedClient(channel, client)) {
이거 위치 한번 확인 부탁드려요~ isInviteMode 하고나서 if else 로 찢어야 할 것 같습니다!

2023-03-26 06:33 UTC, chaejin-jen approved these changes
최고 멋있어요 고생하셨습니다

2023-03-26 06:33 UTC, Kimhan-nah commented on src/controller/Executor.cpp
> +                   !channel_controller.isInvitedClient(channel, client)) {
invite mode가 켜져있을 경우 invite 받지 못한 클라이언트가 join을 시도하려는 경우에 join이 실패되어야 합니다!
그래서 && 연산으로 invite 모드가 켜져있는데 초대받지 못한 경우를 확인해줬습니당

2023-03-26 06:33 UTC, Kimhan-nah commented on src/controller/ChannelController.cpp
> +    std::set<Client *> invited_clients = channel->getInvitedClients();
좋아요!

2023-03-26 06:33 UTC, merged